### ISSUE TITLE
maintenance of memory addresses

### ISSUE THREAD

**Issue by WAZAAAAA0** [rougelite/SCUFFLE#2]
One of the TekkenBotPrime forks had a comfortable .ini override for the memory addresses file which made it easier to update compiled versions (https://github.com/wT-/TekkenBot/commits/master).

It would be cool if you provided instructions on how to find the addresses that make the bot work so that other people can update them in the future after a patch in case you go MIA (have a wiki page like this maybe https://github.com/WAZAAAAA0/TekkenBot/wiki/How-to-update-addresses).

**Comment by rougelite** [comment]
Oh hey, it's the developer who kept TekkenBot alive. You're a good person. 

That's a good idea, I'll see about providing some documentation. I might wait until the 2B patch to get an idea of the scope of the changes. So far, there's been two steam patches and the first one shifted only the global addresses like 16 bytes and the second one didn't change any addresses, so there's a faint possibility their build process could end up being less disruptive than Tekken's.

**Comment by rougelite** [comment]
Config/address.ini now holds all relevant addresses and instructions for finding and updating them with cheat engine.

**Comment by WAZAAAAA0** [comment]
mm hold up, where is address.ini? Can you make an example file maybe?

**Comment by rougelite** [comment]
It should be generated the first time you run SCUFFLE.
