### ISSUE TITLE
I think WHIFF # is incorrect in ver.0.06 to 0.1.1

### ISSUE THREAD

**Issue by SilentWally** [rougelite/SCUFFLE#3]
Hi rougelite, your SCUFFLE app is awesome. It is very helpful to the SC community. Anyway, I'm a guy who concerns about the frame data from 8wayrun.com. I noticed that the WHIFF # is changed from ver.0.0.6 to latest version. And I think the WHIFF # is correct in ver.0.0.5. I don't know if you know the changes or not. 
Thank you. Have a good day.

**Comment by rougelite** [comment]
Yeah, it seems to be displaying (total frames - startup) instead of (total frames - early cancelable frames). Should be fixed in the next version.

**Comment by SilentWally** [comment]
I have tried ver.0.1.2. I'm very satisfied the result. The WHIFF# is correct now. You also added REC# and GAP# that is a bonus for me. Thank you.
